# Generated by Django 5.1.2 on 2024-11-18 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='logo',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='esrb_rating',
            field=models.CharField(blank=True, default='No data', max_length=255),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='rating',
            field=models.CharField(blank=True, default='No data', max_length=5),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='short_screenshots',
            field=models.CharField(blank=True, default='No data', max_length=3000),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='stores',
            field=models.CharField(blank=True, default='No data', max_length=500),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='tags',
            field=models.CharField(blank=True, default='No data', max_length=1000),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='userCollections',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='gameId',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='genres',
            field=models.CharField(blank=True, default='No data', max_length=100),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='imageBackground',
            field=models.CharField(blank=True, default='No data', max_length=1000),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='metacritic',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='platform',
            field=models.CharField(blank=True, default='No data', max_length=100),
        ),
    ]
