# Generated by Django 5.1.2 on 2024-11-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameinfo',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='gameinfo',
            name='stores',
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='gameId',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='imageBackground',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gameinfo',
            name='metacritic',
            field=models.IntegerField(null=True),
        ),
    ]
