# Generated by Django 5.1.2 on 2024-11-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_remove_gameinfo_rating_remove_gameinfo_stores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='platform',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
