# Generated by Django 5.1.2 on 2024-12-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='metacritic',
            field=models.IntegerField(),
        ),
    ]
