# Generated by Django 5.1.2 on 2024-11-04 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_alter_gameinfo_platform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameinfo',
            old_name='genre',
            new_name='genres',
        ),
    ]
