# Generated by Django 5.1.2 on 2024-12-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0004_rename_releasedate_unreleasedgamesinfo_released'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unreleasedgamesinfo',
            name='genres',
            field=models.CharField(blank=True, default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unreleasedgamesinfo',
            name='platform',
            field=models.CharField(blank=True, default=123, max_length=100),
            preserve_default=False,
        ),
    ]
