# Generated by Django 5.1.2 on 2024-12-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0005_alter_unreleasedgamesinfo_genres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='released',
            field=models.DateField(max_length=100),
        ),
        migrations.AlterField(
            model_name='unreleasedgamesinfo',
            name='released',
            field=models.DateField(max_length=100),
        ),
    ]
